### ISSUE TITLE
Can't run webdriver tests on latest wptrunner in servo

### ISSUE THREAD

**Issue by jdm** [w3c/wptrunner#201]
This isn't a regression, because we haven't been able to run them before, but I figured I would resurrect the effort to make it work:
```
godot2:servo jdm$ ./mach test-wpt tests/wpt/web-platform-tests/webdriver/contexts.py
Running 1 tests in web-platform-tests

STDERR: Traceback (most recent call last):
  File "/Users/jdm/src/servo/tests/wpt/harness/wptrunner/testrunner.py", line 142, in start_runner
    executor = executor_cls(browser, **executor_kwargs)
  File "/Users/jdm/src/servo/tests/wpt/harness/wptrunner/executors/executorservo.py", line 340, in __init__
    self.protocol = ServoWdspecProtocol(self, browser)
  File "/Users/jdm/src/servo/tests/wpt/harness/wptrunner/executors/executorservo.py", line 288, in __init__
    self.do_delayed_imports()
  File "/Users/jdm/src/servo/tests/wpt/harness/wptrunner/executors/executorservo.py", line 329, in do_delayed_imports
    from . import pytestrunner
  File "/Users/jdm/src/servo/tests/wpt/harness/wptrunner/executors/pytestrunner/__init__.py", line 5, in <module>
    from . import fixtures
  File "/Users/jdm/src/servo/tests/wpt/harness/wptrunner/executors/pytestrunner/fixtures.py", line 5, in <module>
    from tools import pytest
ImportError: cannot import name pytest
```

**Comment by jdm** [comment]
cc @andreastt

**Comment by jdm** [comment]
This is my sys.path before the `from . import pytestrunner`:
```
['/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/webdriver', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/pytest', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/py', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/pywebsocket/src', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/wptserve', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/html5lib', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/six', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/webdriver', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/pytest', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/py', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/pywebsocket/src', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/wptserve', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/html5lib', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/six', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/webdriver', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/pytest', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/py', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/pywebsocket/src', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/wptserve', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/html5lib', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools/six', '/Users/jdm/src/servo/tests/wpt/web-platform-tests/tools', u'/Users/jdm/src/servo/tests/wpt/web-platform-tests', '/Users/jdm/src/servo/tests/wpt/tests/tools/scripts', '/Users/jdm/src/servo/tests/wpt/harness', u'/Users/jdm/src/servo/python/tidy', u'/Users/jdm/src/servo/tests/wpt', u'/Users/jdm/src/servo/tests/wpt/harness', '/Users/jdm/src/servo/python/tidy', u'/Users/jdm/src/servo/python/_virtualenv/lib/python2.7/site-packages', u'/Users/jdm/src/servo/python', '/Users/jdm/src/servo', '/usr/local/lib/python2.7/site-packages/cssselect-0.9.1-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/macholib-1.7-py2.7.egg', '/usr/local/lib/python2.7/site-packages/modulegraph-0.12.1-py2.7.egg', '/usr/local/lib/python2.7/site-packages/altgraph-0.12-py2.7.egg', '/usr/local/lib/python2.7/site-packages/cvsanaly2-2.1.0-py2.7.egg', '/usr/local/lib/python2.7/site-packages/cssselect-0.9.1-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_Social-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_EventKit-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_Accounts-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_StoreKit-3.0.4-py2.7-macosx-10.9-x86_64.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_CoreWLAN-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_ServiceManagement-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_CoreLocation-3.0.4-py2.7-macosx-10.9-x86_64.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_AppleScriptObjC-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_ScriptingBridge-3.0.4-py2.7-macosx-10.9-x86_64.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_QTKit-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_PubSub-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_InstantMessage-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_InputMethodKit-3.0.4-py2.7-macosx-10.9-x86_64.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_DictionaryServices-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_Collaboration-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_CalendarStore-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_FSEvents-3.0.4-py2.7-macosx-10.9-x86_64.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_WebKit-3.0.4-py2.7-macosx-10.9-x86_64.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_SystemConfiguration-3.0.4-py2.7-macosx-10.9-x86_64.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_SyncServices-3.0.4-py2.7-macosx-10.9-x86_64.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_SearchKit-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_ScreenSaver-3.0.4-py2.7-macosx-10.9-x86_64.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_Quartz-3.0.4-py2.7-macosx-10.9-x86_64.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_PreferencePanes-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_LaunchServices-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_LatentSemanticMapping-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_InstallerPlugins-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_ExceptionHandling-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_DiskArbitration-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_CoreText-3.0.4-py2.7-macosx-10.9-x86_64.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_CoreData-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_Cocoa-3.0.4-py2.7-macosx-10.9-x86_64.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_CFNetwork-3.0.4-py2.7-macosx-10.9-x86_64.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_Automator-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_AppleScriptKit-3.0.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_framework_AddressBook-3.0.4-py2.7-macosx-10.9-x86_64.egg', '/usr/local/lib/python2.7/site-packages/pyobjc_core-3.0.4-py2.7-macosx-10.9-x86_64.egg', '/usr/local/lib/python2.7/site-packages/py2app-0.9-py2.7.egg', '/usr/local/lib/python2.7/site-packages/macholib-1.7-py2.7.egg', '/usr/local/lib/python2.7/site-packages/modulegraph-0.12.1-py2.7.egg', '/usr/local/lib/python2.7/site-packages/altgraph-0.12-py2.7.egg', '/Users/jdm/src/servo', '/usr/local/lib/python2.7/site-packages', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/usr/local/Cellar/protobuf/2.6.1/libexec/lib/python2.7/site-packages', '/Library/Python/2.7/site-packages', u'./components/style/properties/Mako-0.9.1.zip', '/Users/jdm/src/servo/tests/wpt/harness']
```

**Comment by jdm** [comment]
My theory is that it's picking up the wrong `tools` module.

**Comment by jdm** [comment]
I tried modifying sys.path to have variations on web-platform/tests/tools/pytest as the first entry, and nothing changed. I also tried renaming css-tests/tools to something else to ensure that it wasn't being used, and still no changed. I'm completely out of my depth when it comes to this problem now :)

**Comment by jdm** [comment]
I tried modify do_delayed_imports in environment.py which imports tools.serve (and verified that `serve_root` is the `web-platform-tests` directory, and importing pytest or webdriver from tools there, and it doesn't work. I don't understand what's going on at all.

**Comment by gsnedders** [comment]
It needs `/Users/jdm/src/servo/tests/wpt/web-platform-tests` on the path. Somehow.

**Comment by jdm** [comment]
Even when I explicitly added that it didn't work.
